/*-------------------------------------------------------------------------
 *
 * pg_optimized_table_metadata_d.h
 *    Macro definitions for pg_optimized_table_metadata
 *
 * Portions Copyright (c) 1996-2024, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/backend/catalog/genbki.pl
 *
 *-------------------------------------------------------------------------
 */
#ifndef PG_OPTIMIZED_TABLE_METADATA_D_H
#define PG_OPTIMIZED_TABLE_METADATA_D_H

#define OptimizedTableMetadataRelationId 12345
#define OptimizedTableMetadataRelidIndexId 12346

#define Anum_pg_optimized_table_metadata_relid 1
#define Anum_pg_optimized_table_metadata_fixed_col_count 2
#define Anum_pg_optimized_table_metadata_var_col_count 3
#define Anum_pg_optimized_table_metadata_fixed_col_offsets 4

#define Natts_pg_optimized_table_metadata 4

#endif                            /* PG_OPTIMIZED_TABLE_METADATA_D_H */